name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.0
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - uses: actions/cache@v2
      with:
        path: Podcasts.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - uses: actions/checkout@v2
    - name: Decrypt
      run: ./scripts/decrypt.sh
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
    - name: Bootstrap
      run: ./scripts/bootstrap.sh
    - name: Run test
      run: ./scripts/test.sh
