name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.0
    - uses: actions/checkout@v2
    - name: Decrypt
      run: ./scripts/decrypt.sh
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
    - name: Bootstrap
      run: ./scripts/bootstrap.sh
    - name: Run test
      run: ./scripts/test.sh
